### ISSUE TITLE
Import Images

### ISSUE THREAD

**Issue by jprein** [ccp-eva/vox#30]

**Comment by Kalaschnik** [comment]
If you get this errors on mac as in https://github.com/nodejs/node-gyp/issues/1927

Perform:
1. Install full Xcode
2. Open Xcode and the CLT will install
3. Then run sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

Then install:
1. `npm install sharp -D``
2. `npm install @parcel/transformer-image@2.0.0-nightly.2220 -D`

**Comment by Kalaschnik** [comment]
Dafuq; there is an Image constructur...
https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/Image

that means:
```javascript
const element = document.createElement('div');
const myIcon = new Image();
myIcon.src = Icon;
```
