### ISSUE TITLE
Attach button class to all "g id" elements that contain "button" in the string

### ISSUE THREAD

**Issue by jprein** [ccp-eva/vox#7]
For same styling for all buttons, create class for every button element. 
This could also allow for automatically traversing through the slides (based on array of slides that was defined).
Button knows its parent slide, so it knows its position﻿

https://www.google.com/search?q=apply+css+style+to+svg&oq=css+style+to+svg&aqs=chrome.1.69i57j0i22i30l6.7258j0j1&sourceid=chrome&ie=UTF-8

**Comment by Kalaschnik** [comment]
Closed, as its progress is being tracked in #24
